### ISSUE TITLE
iPhone X ios12.1 返回和选择不显示

### ISSUE THREAD

**Issue by zhihaozhang** [RainManGO/ZYimagePickerPodDemo#1]
感谢您提供的demo，我目前遇到的问题是预览图片时Tab上的返回和选中按钮不见了。请问该如何解决呢？我的设备是iPhone X，iOS12.1
![5661545117423_ pic](https://user-images.githubusercontent.com/4500659/50137998-00bba600-02d8-11e9-9eba-c7f1b6403d7f.jpg)

**Comment by RainManGO** [comment]
不好意思，那么晚才看到。我这边现在没有iphonex真机，用iphonex  12.1模拟器没有发现这个问题。我修改了代码，有空更新下代码帮忙再看下还有这问题吗？感谢。

**Comment by zhihaozhang** [comment]
没事，谢谢回复，我明天更新看看。

**Comment by zhihaozhang** [comment]
谢谢，这个问题确实解决了，但是引入了新的问题，我提了新issue，麻烦看一下。
