### ISSUE TITLE
选择若干图片后，点击某张图片进去，然后点左上角的返回，会出现闪退

### ISSUE THREAD

**Issue by zhihaozhang** [RainManGO/ZYimagePickerPodDemo#2]
如题，经查，是触发了ZYPhotoPreviewDeleteViewController的第79行assert，麻烦fix一下~
 override func backClick(button: UIButton) {
        if self.presentedViewController != nil {
            self.dismiss(animated: true, completion: nil)
        }else{
·            assert(self.navigationController != nil, "外界需要modal的方式进来")
            if self.navigationController != nil{
                self.navigationController?.popViewController(animated: true)
            }
        }
    }

**Comment by RainManGO** [comment]
已修复，谢谢您的测试。
